#Set the cooldown timer for tip notification
cooldown: 60000
#
#
#How many times should it try to find a tip before giving up
#Set this higher if you disable tip sources
number-tries: 5
#Do you want tips about player commands
command: true
#If command is true what commands do you want to not track
ignored-commands:
- kick
- ban
- tempban
- lookup
#Do you want tips about pvp
pvp: true
#Do you want tips for players Location
location: true
#Do you want tips about players with low health
health: true
#Do you want tips about players inventories
inventory: true
#Do you want tips about players chests
chest: true
#Do you want tips about heroes skills
heroes: true
#Do you want tips about chestshop purchases
chestshop: true
