author: multitallented
database: false
description: Drops hints to players about other players' pvping, coordinates, chests,
  inventories, purchases, commands.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: multitallented.plugins.herograpevine.HeroGrapevine
name: HeroGrapevine
startup: postworld
version: '1.1'
commands:
   herograpevine:
      description: Toggles recieving incoming tips
      usage: /<command> toggle
permissions:
   toggle:
      description: Allows you to toggle recieving tips on or off. You cant recieve tips without this.
      default: op
   bypass:
      description: Disables incoming tips
      default: false